WIDTH = 800
HEIGHT = 600
SCREEN_SIZE = (WIDTH, HEIGHT)
SCREEN_CENTER = (WIDTH // 2, HEIGHT // 2)
NEGRO = (0, 0, 0)
COLOR_FONDO = (10, 10, 10)
BLANCO = (255, 255, 255)

ESCALA_PERSONAJES = 0.3
ESCALA_BALA = 0.8

FPS = 60
SPEED_BULLET = 4
CANT_ENEMIGOS = 5

TILE_SIZE = 19

R_EXTRAS = 0
R_IMAGENES_TITLE = 1
R_IMAGENES_INSTRUCTIONS = 2
R_IMAGENES_OVER = 3
R_IMAGENES_VICTORY = 4
R_JUMPSCARE_FREDDY = 5
R_JUMPSCARE_BONNIE = 6
R_JUMPSCARE_CHICA = 7
R_JUMPSCARE_FOXY = 8
R_JUMPSCARE_PUPPET = 9
R_PERSONAJES = 10
R_AUDIO = 11
R_FUENTE = 12
R_CORAZONES = 13